// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hnnxnmwvuwvmvppcsnnc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhubnhubXd2dXd2bXZwcGNzbm5jIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgzMDY2ODAsImV4cCI6MjA2Mzg4MjY4MH0.nrtEGrY0q1Vqitsop9Qum1GRHVAh0MlNZsWNd2fMfC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);